name: example
description: An example usage of barrel_files package
publish_to: none

version: 0.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  barrel_files_annotation: ^0.1.1

dev_dependencies:
  barrel_files: ^0.1.1
  build_runner: ^2.7.0
  flutter_lints: ^6.0.0
