name: example
description: An example usage of barrel_files package
publish_to: none

version: 0.0.1+1

environment:
  sdk: ^3.0.0

dependencies:
  barrel_files_annotation:
    path: ../barrel_files_annotation

dev_dependencies:
  barrel_files:
    path: ../barrel_files_generator
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
