name: barrel_files_annotation
description: Annotations for the barrel_files package; Generate barrel files for Dart and Flutter packages with build_runner based on code annotations
repository: https://github.com/foxanna/barrel_files
issue_tracker: https://github.com/foxanna/barrel_files/issues

version: 0.1.0

environment:
  sdk: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.3
