name: barrel_files
description: Barrel files generator
publish_to: none

version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.1
  barrel_files_annotation:
    path: ../barrel_files_annotation
  code_builder: ^4.7.0
  dartx: ^1.2.0
  dart_style: ^2.3.3
  file: ^7.0.0
  glob: ^2.1.2
  source_gen: ^1.4.0
  yaml: ^3.1.2

dev_dependencies:
  build_test: ^2.2.1
  flutter_lints: ^2.0.3
  test: ^1.24.7
