name: barrel_files
description: Generate barrel files for Dart and Flutter packages with build_runner based on code annotations
repository: https://github.com/foxanna/barrel_files
issue_tracker: https://github.com/foxanna/barrel_files/issues
topics:
  - barrel-files
  - build-runner
  - codegen

version: 0.2.0

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^7.0.0
  build: ^3.0.2
  barrel_files_annotation: ^0.2.0
  code_builder: ^4.10.1
  dartx: ^1.2.0
  dart_style: ^3.1.1
  file: ^7.0.1
  glob: ^2.1.3
  logging: ^1.3.0
  source_gen: ^3.0.0
  yaml: ^3.1.3

dev_dependencies:
  build_test: ^3.3.2
  flutter_lints: ^6.0.0
  test: ^1.26.3
