name: barrel_files
description: Generate barrel files for Dart and Flutter packages with build_runner based on code annotations
repository: https://github.com/foxanna/barrel_files
issue_tracker: https://github.com/foxanna/barrel_files/issues
topics:
  - barrel-files
  - build-runner
  - codegen

version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.1
  barrel_files_annotation: ^0.1.0
  code_builder: ^4.7.0
  dartx: ^1.2.0
  dart_style: ^2.3.3
  file: ^7.0.0
  glob: ^2.1.2
  source_gen: ^1.4.0
  yaml: ^3.1.2

dev_dependencies:
  build_test: ^2.2.1
  flutter_lints: ^2.0.3
  test: ^1.24.7
